version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./Logs:/app/Logs

volumes:
  mongo-data:
  mongo-test-data:

